### ISSUE TITLE
Encrypted Backup to Google Drive

### ISSUE THREAD

**Issue by szaimen** [Criptext/Android-Email-Client#501] opened 2019-06-22 16:55 UTC
Please add support for encrypted Backups to Google Drive.
Even better would be webdav-support for Backups.

**Comment by jorgeblacio** [comment] 2019-06-25 15:06
Hi @szaimen thanks for the suggestion. We are currently looking to have encrypted backup for Googler Drive and also have a way to export your data locally so that you can save it wherever you want. We'll update this issue as soon as I have an ETA for that update.

**Comment by jorgeblacio** [comment] 2019-08-16 21:54
This is now out on version 0.21.0+, so I'll close this issue.

**Closed by jorgeblacio** 2019-08-16 21:54 UTC

**Comment by szaimen** [comment] 2019-08-16 22:26
Please reopen the issue. 
In my version (I am running 0.21.3) encrypted Backups are possible but not to Google Drive.
So this issue isn't solved yet.

**Comment by jorgeblacio** [comment] 2019-08-17 03:49
Hi @szaimen you can export an encrypted backup to Google drive manually and it will work as intended. But the thing is, for automatic backups we cannot do this, since we would either have to ask you for a password each time, which beats the purpose of automated background backups, or we would have to ask the password once and save it in the local database or storage, which will be going against our policy of ensuring the user's privacy. That's why we chose not to provide encrypted automated Google Drive backups.

**Comment by szaimen** [comment] 2019-08-17 09:00
Okay
